In [4]:
import pandas as pd
from io import StringIO

def expand_table_with_missing_bpm(df):
    # Skip the first two rows (header and units)
    data = df.iloc[1:].copy()
    
    # Convert columns to numeric where applicable
    data['HR'] = pd.to_numeric(data['HR'], errors='coerce')
    data['Calories'] = pd.to_numeric(data['Calories'], errors='coerce')
    
    # Create a list to store expanded rows
    expanded_rows = []
    
    # Iterate through rows to interpolate missing BPM values
    for i in range(len(data) - 1):
        current_row = data.iloc[i]
        next_row = data.iloc[i + 1]
        
        current_bpm = current_row['HR']
        next_bpm = next_row['HR']
        
        # Add the current row to the expanded rows
        expanded_rows.append(current_row)
        
        # Check if there are missing BPM values
        if next_bpm - current_bpm > 1:
            missing_bpm_count = int(next_bpm - current_bpm - 1)
            calorie_diff = (next_row['Calories'] - current_row['Calories']) / (missing_bpm_count + 1)
            
            # Generate missing rows
            for j in range(1, missing_bpm_count + 1):
                interpolated_bpm = current_bpm + j
                interpolated_calories = current_row['Calories'] + calorie_diff * j
                
                # Create a new row with interpolated values
                interpolated_row = current_row.copy()
                interpolated_row['HR'] = interpolated_bpm
                # Calculate calories per second based on the interpolated value
                interpolated_row['Calories'] = interpolated_calories
                
                # Add the interpolated row to the expanded rows
                expanded_rows.append(interpolated_row)
    
    # Add the last row to the expanded rows
    last_row = data.iloc[-1].copy()
    expanded_rows.append(last_row)
    
    # Convert the list of rows back to a DataFrame
    expanded_data = pd.DataFrame(expanded_rows)

    # Add a new column for calories per minute
    expanded_data['Calories_Second'] = expanded_data['Calories'] / 60
    
    return expanded_data

def import_to_duckdb(df, table_name, db_file='workout_data.db', replace=False):
    """
    Import a pandas DataFrame into a DuckDB table.
    
    Parameters:
    -----------
    df : pandas.DataFrame
        The DataFrame to import into DuckDB
    table_name : str
        Name for the DuckDB table
    db_file : str, optional
        Path to DuckDB database file (default: 'workout_data.db')
    replace : bool, optional
        Whether to replace an existing table (default: False)
    
    Returns:
    --------
    duckdb.DuckDBPyConnection
        The active DuckDB connection
    """
    import duckdb
    
    # Create a DuckDB connection
    con = duckdb.connect(db_file)
    
    # Check if table exists and handle accordingly
    table_exists = con.execute(f"SELECT count(*) FROM information_schema.tables WHERE table_name='{table_name}'").fetchone()[0] > 0
    
    if table_exists:
        if replace:
            con.execute(f"DROP TABLE IF EXISTS {table_name}")
        else:
            print(f"Table '{table_name}' already exists. Set replace=True to overwrite.")
            return con
    
    # Import the DataFrame into a DuckDB table
    con.execute(f"CREATE TABLE {table_name} AS SELECT * FROM df")
    
    # Verify the import
    count = con.execute(f"SELECT COUNT(*) FROM {table_name}").fetchone()[0]
    print(f"Data imported to DuckDB table '{table_name}' with {count} rows")
    
    con.close()

In [5]:
import pandas as pd
from io import StringIO

# Read the CSV data into a DataFrame
# df = pd.read_csv(StringIO(csv_data), sep="\t")
df = pd.read_csv("./v02max_data.csv")
#print(df)

# Keep only HR and Calories columns
df = df[['HR', 'Calories']]

# Print to total count
print(f"Total rows in original DataFrame: {len(df)}")

# Expand the table
expanded_df = expand_table_with_missing_bpm(df)
print(f"Total rows in expanded DataFrame: {len(expanded_df)}")

# Set display options to show all rows and columns without truncation
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.float_format', '{:.6f}'.format)

# Find the index of the maximum HR value in expanded_df
# The reason we want to have a subset till max value is
# because after maxing out HR, after that we will have duplicates but different calory burn.
# Different calories burn because the body is cooling down.
max_hr_value = expanded_df['HR'].max()
max_hr_index = expanded_df[expanded_df['HR'] == max_hr_value].index[0]

print(f"Maximum HR value in expanded_df: {max_hr_value} at index {max_hr_index}")

# Create a subset of the expanded DataFrame from index 0 to the index of maximum HR
hr_rise_expanded_df = expanded_df.loc[:max_hr_index]
print(f"Total rows in expanded sliced (0:{max_hr_index}) DataFrame : {len(hr_rise_expanded_df)}")

# Calculate the average calorie difference b/n bpm
# TODO

# Sorting it because we can have the following sequence of HR
# e.g., 150, 151, 152, 151, 150.
# Sorting it will put all the same HR values next to each other, so the collapsing algo
# below will be able to collapse them properly.
hr_rise_expanded_df = hr_rise_expanded_df.sort_values(by='HR').reset_index(drop=True)

# Display the subset of expanded DataFrame (data up to max HR)
print("\nExpanded data from HR rise (index 0 to max HR):")
display(hr_rise_expanded_df)

# Now continue with the collapsing process
# Create a group identifier for consecutive identical HR values
hr_rise_expanded_df['group'] = (hr_rise_expanded_df['HR'] != hr_rise_expanded_df['HR'].shift()).cumsum()

# Group by both group and HR to collapse only consecutive duplicates
collapsed_df = hr_rise_expanded_df.groupby(['group', 'HR']).agg({
    'Calories': 'mean',
    'Calories_Second': 'mean'
}).reset_index().drop('group', axis=1)
print(f"Total rows in collapsed DataFrame: {len(collapsed_df)}")

# Display the collapsed DataFrame
print("\nFull collapsed DataFrame:")
display(collapsed_df)

# Write the collapsed DataFrame to DuckDB
db_dir = './hr_data/database_v2.duckdb'
import_to_duckdb(collapsed_df, 'calories_per_hr', db_dir, replace=True)

Total rows in original DataFrame: 85
Total rows in expanded DataFrame: 126
Maximum HR value in expanded_df: 185.0 at index 72
Total rows in expanded sliced (0:72) DataFrame : 114

Expanded data from HR rise (index 0 to max HR):

            HR  Calories  Calories_Second
0    96.000000  2.330000         0.038833
1    97.000000  2.485000         0.041417
2    98.000000  2.640000         0.044000
3    99.000000  2.795000         0.046583
4   100.000000  2.950000         0.049167
5   101.000000  3.105000         0.051750
6   102.000000  3.260000         0.054333
7   103.000000  3.415000         0.056917
8   104.000000  3.570000         0.059500
9   105.000000  3.725000         0.062083
10  106.000000  3.880000         0.064667
11  107.000000  3.950000         0.065833
12  108.000000  4.380000         0.073000
13  109.000000  4.461429         0.074357
14  110.000000  4.542857         0.075714
15  111.000000  4.624286         0.077071
16  112.000000  4.705714         0.078429
17  113.000000  4.787143         0.079786
18  114.000000  4.868571         0.081143
19  115.000000  4.950000         0.082500
20  116.000000  5.662500         0.094375
21  117.000000  6.375000         0.106250
22  118.000000  7.087500         0.118125
23  119.000000  7.800000         0.130000
24  120.000000  7.847500         0.130792
25  121.000000  7.895000         0.131583
26  122.000000  7.942500         0.132375
27  123.000000  7.990000         0.133167
28  124.000000  8.920000         0.148667
29  125.000000  9.030000         0.150500
30  126.000000  9.140000         0.152333
31  127.000000  9.250000         0.154167
32  128.000000  9.360000         0.156000
33  129.000000  9.470000         0.157833
34  130.000000  9.666000         0.161100
35  131.000000  9.862000         0.164367
36  132.000000 10.058000         0.167633
37  133.000000 10.254000         0.170900
38  134.000000 10.450000         0.174167
39  134.000000  9.820000         0.163667
40  134.000000  9.920000         0.165333
41  135.000000 10.380000         0.173000
42  135.000000 11.050000         0.184167
43  136.000000  9.920000         0.165333
44  137.000000 10.180000         0.169667
45  138.000000 10.440000         0.174000
46  139.000000 10.700000         0.178333
47  140.000000 12.090000         0.201500
48  140.000000 10.970000         0.182833
49  141.000000  9.880000         0.164667
50  142.000000 12.840000         0.214000
51  143.000000 10.710000         0.178500
52  144.000000 10.725000         0.178750
53  145.000000 10.740000         0.179000
54  146.000000 11.456667         0.190944
55  147.000000 12.173333         0.202889
56  148.000000 11.830000         0.197167
57  148.000000 12.890000         0.214833
58  149.000000 12.740000         0.212333
59  150.000000 13.650000         0.227500
60  151.000000 12.295000         0.204917
61  152.000000 10.940000         0.182333
62  152.000000 13.680000         0.228000
63  152.000000 14.060000         0.234333
64  152.000000 12.410000         0.206833
65  153.000000 11.070000         0.184500
66  153.000000 14.050000         0.234167
67  154.000000 13.890000         0.231500
68  155.000000 12.600000         0.210000
69  156.000000 13.220000         0.220333
70  157.000000 14.115000         0.235250
71  158.000000 15.010000         0.250167
72  159.000000 15.200000         0.253333
73  159.000000 15.020000         0.250333
74  160.000000 15.105000         0.251750
75  160.000000 14.560000         0.242667
76  161.000000 15.190000         0.253167
77  161.000000 14.540000         0.242333
78  161.000000 15.480000         0.258000
79  162.000000 16.000000         0.266667
80  163.000000 16.520000         0.275333
81  164.000000 14.890000         0.248167
82  165.000000 14.620000         0.243667
83  166.000000 14.500000         0.241667
84  166.000000 17.720000         0.295333
85  166.000000 16.530000         0.275500
86  167.000000 17.230000         0.287167
87  168.000000 16.710000         0.278500
88  169.000000 14.050000         0.234167
89  170.000000 17.640000         0.294000
90  170.000000 17.740000         0.295667
91  171.000000 18.220000         0.303667
92  172.000000 18.700000         0.311667
93  173.000000 17.140000         0.285667
94  174.000000 16.855000         0.280917
95  174.000000 19.320000         0.322000
96  175.000000 16.570000         0.276167
97  175.000000 18.690000         0.311500
98  176.000000 18.300000         0.305000
99  176.000000 18.140000         0.302333
100 176.000000 15.610000         0.260167
101 176.000000 18.180000         0.303000
102 177.000000 18.780000         0.313000
103 177.000000 18.100000         0.301667
104 178.000000 19.100000         0.318333
105 179.000000 18.100000         0.301667
106 180.000000 20.290000         0.338167
107 181.000000 19.260000         0.321000
108 182.000000 19.640000         0.327333
109 182.000000 19.360000         0.322667
110 183.000000 20.410000         0.340167
111 183.000000 20.630000         0.343833
112 184.000000 20.125000         0.335417
113 185.000000 19.620000         0.327000

Total rows in collapsed DataFrame: 90

Full collapsed DataFrame:

           HR  Calories  Calories_Second
0   96.000000  2.330000         0.038833
1   97.000000  2.485000         0.041417
2   98.000000  2.640000         0.044000
3   99.000000  2.795000         0.046583
4  100.000000  2.950000         0.049167
5  101.000000  3.105000         0.051750
6  102.000000  3.260000         0.054333
7  103.000000  3.415000         0.056917
8  104.000000  3.570000         0.059500
9  105.000000  3.725000         0.062083
10 106.000000  3.880000         0.064667
11 107.000000  3.950000         0.065833
12 108.000000  4.380000         0.073000
13 109.000000  4.461429         0.074357
14 110.000000  4.542857         0.075714
15 111.000000  4.624286         0.077071
16 112.000000  4.705714         0.078429
17 113.000000  4.787143         0.079786
18 114.000000  4.868571         0.081143
19 115.000000  4.950000         0.082500
20 116.000000  5.662500         0.094375
21 117.000000  6.375000         0.106250
22 118.000000  7.087500         0.118125
23 119.000000  7.800000         0.130000
24 120.000000  7.847500         0.130792
25 121.000000  7.895000         0.131583
26 122.000000  7.942500         0.132375
27 123.000000  7.990000         0.133167
28 124.000000  8.920000         0.148667
29 125.000000  9.030000         0.150500
30 126.000000  9.140000         0.152333
31 127.000000  9.250000         0.154167
32 128.000000  9.360000         0.156000
33 129.000000  9.470000         0.157833
34 130.000000  9.666000         0.161100
35 131.000000  9.862000         0.164367
36 132.000000 10.058000         0.167633
37 133.000000 10.254000         0.170900
38 134.000000 10.063333         0.167722
39 135.000000 10.715000         0.178583
40 136.000000  9.920000         0.165333
41 137.000000 10.180000         0.169667
42 138.000000 10.440000         0.174000
43 139.000000 10.700000         0.178333
44 140.000000 11.530000         0.192167
45 141.000000  9.880000         0.164667
46 142.000000 12.840000         0.214000
47 143.000000 10.710000         0.178500
48 144.000000 10.725000         0.178750
49 145.000000 10.740000         0.179000
50 146.000000 11.456667         0.190944
51 147.000000 12.173333         0.202889
52 148.000000 12.360000         0.206000
53 149.000000 12.740000         0.212333
54 150.000000 13.650000         0.227500
55 151.000000 12.295000         0.204917
56 152.000000 12.772500         0.212875
57 153.000000 12.560000         0.209333
58 154.000000 13.890000         0.231500
59 155.000000 12.600000         0.210000
60 156.000000 13.220000         0.220333
61 157.000000 14.115000         0.235250
62 158.000000 15.010000         0.250167
63 159.000000 15.110000         0.251833
64 160.000000 14.832500         0.247208
65 161.000000 15.070000         0.251167
66 162.000000 16.000000         0.266667
67 163.000000 16.520000         0.275333
68 164.000000 14.890000         0.248167
69 165.000000 14.620000         0.243667
70 166.000000 16.250000         0.270833
71 167.000000 17.230000         0.287167
72 168.000000 16.710000         0.278500
73 169.000000 14.050000         0.234167
74 170.000000 17.690000         0.294833
75 171.000000 18.220000         0.303667
76 172.000000 18.700000         0.311667
77 173.000000 17.140000         0.285667
78 174.000000 18.087500         0.301458
79 175.000000 17.630000         0.293833
80 176.000000 17.557500         0.292625
81 177.000000 18.440000         0.307333
82 178.000000 19.100000         0.318333
83 179.000000 18.100000         0.301667
84 180.000000 20.290000         0.338167
85 181.000000 19.260000         0.321000
86 182.000000 19.500000         0.325000
87 183.000000 20.520000         0.342000
88 184.000000 20.125000         0.335417
89 185.000000 19.620000         0.327000

Data imported to DuckDB table 'calories_per_hr' with 90 rows